// Sample storefront data. Replace with real inventory, photography, sizes and colors.
const products = [
 {id:'w01',name:'Island Bloom Wrap Dress',category:'Women',parent:'Clothing',price:89,description:'A flowing wrap silhouette in a bold botanical print.',sizes:['XS','S','M','L','XL'],colors:['Coral','Ocean'],badge:'Bestseller',art:['#dfb77a','#d9765e','#315843']},
 {id:'m01',name:'Coastal Print Shirt',category:'Men',parent:'Clothing',price:68,description:'Lightweight everyday shirt with a lively island motif.',sizes:['S','M','L','XL'],colors:['Sand','Deep green'],badge:'New',art:['#e5c48b','#73917a','#bd6148']},
 {id:'c01',name:'Little Voyager Set',category:'Children',parent:'Clothing',price:42,description:'A soft, easy-to-wear top and shorts set for little explorers.',sizes:['2Y','4Y','6Y','8Y'],colors:['Sunset','Lagoon'],badge:'',art:['#d7aa74','#e58b69','#54765c']},
 {id:'b01',name:'Tiny Tides Onesie',category:'Baby & Toddler',parent:'Clothing',price:26,description:'Gentle cotton comfort with a playful wave pattern.',sizes:['0–3M','3–6M','6–12M','12–18M'],colors:['Cream','Mint'],badge:'',art:['#d9d3bd','#91a894','#db765d']},
 {id:'a01',name:'Sunrise Over the Lagoon',category:'Paintings',parent:'Artifacts',price:240,description:'Original acrylic painting inspired by a Pacific morning.',sizes:['30 × 40 cm'],colors:['As pictured'],badge:'One of a kind',art:['#e9bf85','#538278','#d8785f']},
 {id:'a02',name:'Hand-carved Tanoa Bowl',category:'Carvings',parent:'Artifacts',price:175,description:'Decorative carved wooden bowl; artisan and wood details to be confirmed.',sizes:['Approx. 28 cm'],colors:['Natural wood'],badge:'Handmade',art:['#b78358','#704832','#d8ad75']},
 {id:'a03',name:'Island Heritage Portrait',category:'Portraits',parent:'Artifacts',price:320,description:'Expressive portrait artwork celebrating Pacific identity.',sizes:['40 × 50 cm'],colors:['As pictured'],badge:'',art:['#b56a4c','#e1b87b','#385f54']},
 {id:'a04',name:'Traditional Fishing Tool',category:'Traditional Tools',parent:'Artifacts',price:95,description:'Display piece inspired by traditional Pacific craftsmanship.',sizes:['Approx. 35 cm'],colors:['Natural finish'],badge:'',art:['#d8bd8c','#867255','#bd7257']},
 {id:'f01',name:'PNG Motif Cotton',category:'PNG Designs',parent:'Fabrics',price:24,description:'Printed cotton fabric sold by the metre; confirm width and care.',sizes:['1 metre'],colors:['Rust','Indigo'],badge:'Per metre',art:['#db8e68','#415c70','#e6c17f']},
 {id:'f02',name:'Tongan Pattern Cloth',category:'Tongan Design',parent:'Fabrics',price:29,description:'Statement fabric with a geometric pattern; sold by the metre.',sizes:['1 metre'],colors:['Red','Black'],badge:'Per metre',art:['#b94f42','#272c2a','#dfb56f']},
 {id:'f03',name:'Fijian Garden Print',category:'Fijian Design',parent:'Fabrics',price:27,description:'A vibrant floral-inspired fabric for clothing and creative projects.',sizes:['1 metre'],colors:['Leaf','Ocean'],badge:'Per metre',art:['#7d9870','#477b79','#e3bd7b']},
 {id:'f04',name:'Artist’s Wave Fabric',category:'Artistic Fabrics',parent:'Fabrics',price:32,description:'Painterly wave print on soft fabric; sold by the metre.',sizes:['1 metre'],colors:['Blue','Coral'],badge:'Per metre',art:['#4b8290','#d6785e','#e8c78f']},
 {id:'h01',name:'Woven Market Basket',category:'Handicrafts',parent:'Handicrafts',price:58,description:'Handwoven basket for market days, picnics and everyday storage.',sizes:['Small / Medium'],colors:['Natural'],badge:'Handmade',art:['#d5b77e','#a2704d','#627454']},
 {id:'d01',name:'Carved Sun Wall Art',category:'Art Home Deco',parent:'Art Home Deco',price:115,description:'A warm, sculptural accent for a gallery wall or entryway.',sizes:['30 cm diameter'],colors:['Natural / terracotta'],badge:'',art:['#d9b071','#b56550','#495e4d']},
 {id:'fu01',name:'Island Lounge Chair',category:'Furniture',parent:'Furniture',price:485,description:'A statement occasional chair; confirm materials, dimensions and delivery.',sizes:['W 72 × H 78 cm'],colors:['Natural / forest'],badge:'Made to order',art:['#c4a27a','#43644f','#d68563']}
];
const $=s=>document.querySelector(s);const grid=$('#productGrid'),template=$('#productTemplate');let currentCategory='All',cart=JSON.parse(localStorage.getItem('islandTreasuresCart')||'[]');
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)}
function categoryList(){return ['All','Clothing','Women','Men','Children','Baby & Toddler','Artifacts','Paintings','Carvings','Portraits','Traditional Tools','Fabrics','PNG Designs','Tongan Design','Fijian Design','Artistic Fabrics','Handicrafts','Art Home Deco','Furniture']}
function matches(p,c){return c==='All'||p.category===c||p.parent===c}
function render(){let list=products.filter(p=>matches(p,currentCategory));let sort=$('#sortSelect').value;if(sort==='price-low')list.sort((a,b)=>a.price-b.price);if(sort==='price-high')list.sort((a,b)=>b.price-a.price);grid.innerHTML='';$('#shopTitle').textContent=currentCategory==='All'?'Shop all':currentCategory;list.forEach(p=>{let node=template.content.cloneNode(true),card=node.querySelector('.product-card');card.dataset.id=p.id;card.style.setProperty('--art1',p.art[0]);card.style.setProperty('--art2',p.art[1]);card.style.setProperty('--art3',p.art[2]);node.querySelector('.product-badge').textContent=p.badge;node.querySelector('.product-category').textContent=p.category;node.querySelector('.product-color').textContent=p.colors.join(' · ');node.querySelector('.product-name').textContent=p.name;node.querySelector('.product-description').textContent=`${p.description} Sizes: ${p.sizes.join(', ')}.`;node.querySelector('.product-price').textContent=money(p.price);node.querySelector('.qty-minus').onclick=()=>changeQty(card,-1);node.querySelector('.qty-plus').onclick=()=>changeQty(card,1);node.querySelector('.add-button').onclick=()=>addToCart(p.id,Number(card.querySelector('.qty-value').textContent));node.querySelector('.quick-add').onclick=()=>addToCart(p.id,1);node.querySelector('.buy-button').onclick=()=>{addToCart(p.id,Number(card.querySelector('.qty-value').textContent));openCart();setTimeout(openCheckout,260)};grid.append(node)});renderChips()}
function renderChips(){let wrap=$('#categoryChips');wrap.innerHTML='';categoryList().forEach(c=>{let b=document.createElement('button');b.className='chip'+(currentCategory===c?' active':'');b.textContent=c;b.onclick=()=>{currentCategory=c;render();$('#shop').scrollIntoView({behavior:'smooth'})};wrap.append(b)})}
function changeQty(card,d){let el=card.querySelector('.qty-value');el.textContent=Math.max(1,Number(el.textContent)+d)}
function save(){localStorage.setItem('islandTreasuresCart',JSON.stringify(cart));$('#cartCount').textContent=cart.reduce((n,i)=>n+i.qty,0);renderCart()}
function addToCart(id,qty){let item=cart.find(x=>x.id===id);if(item)item.qty+=qty;else cart.push({id,qty});save()}
function renderCart(){let box=$('#cartItems');box.innerHTML='';if(!cart.length){box.innerHTML='<p class="cart-empty">Your bag is ready for something lovely.</p>';$('#subtotal').textContent=money(0);return}let total=0;cart.forEach(i=>{let p=products.find(x=>x.id===i.id);if(!p)return;total+=p.price*i.qty;let row=document.createElement('div');row.className='cart-row';row.style.setProperty('--art1',p.art[0]);row.style.setProperty('--art2',p.art[1]);row.innerHTML=`<div class="cart-thumb">✳</div><div><h3>${p.name}</h3><p>${i.qty} × ${money(p.price)}</p><button class="remove-item" data-id="${p.id}">Remove</button></div><strong>${money(i.qty*p.price)}</strong>`;box.append(row)});$('#subtotal').textContent=money(total);box.querySelectorAll('.remove-item').forEach(b=>b.onclick=()=>{cart=cart.filter(i=>i.id!==b.dataset.id);save()})}
function openCart(){$('#overlay').hidden=false;$('#cartDrawer').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false')};function closeCart(){$('#overlay').hidden=true;$('#cartDrawer').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true')}
function openCheckout(){if(!cart.length)return;let total=cart.reduce((sum,i)=>sum+products.find(p=>p.id===i.id).price*i.qty,0);$('#checkoutSummary').textContent=`${cart.reduce((n,i)=>n+i.qty,0)} item(s) · Subtotal ${money(total)} (shipping and taxes not included)`;$('#checkoutDialog').showModal()}
$('#mainNav').addEventListener('click',e=>{let a=e.target.closest('[data-category]');if(a){e.preventDefault();currentCategory=a.dataset.category;render();$('#shop').scrollIntoView({behavior:'smooth'});$('#mainNav').classList.remove('open');$('#menuToggle').setAttribute('aria-expanded','false')}});document.querySelectorAll('.footer [data-category]').forEach(a=>a.onclick=e=>{e.preventDefault();currentCategory=a.dataset.category;render();$('#shop').scrollIntoView({behavior:'smooth'})});$('#sortSelect').onchange=render;$('#openCart').onclick=openCart;$('#closeCart').onclick=closeCart;$('#overlay').onclick=closeCart;$('#checkoutButton').onclick=()=>{if(!cart.length)return;closeCart();openCheckout()};$('#checkoutForm').addEventListener('submit',e=>{e.preventDefault();alert('Demo only: no order or payment was processed. Connect a payment provider and order-management backend before launch.');$('#checkoutDialog').close()});$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();alert('Demo form only. Connect an email marketing service before launch.');e.target.reset()});$('#menuToggle').onclick=()=>{let open=$('#mainNav').classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',String(open))};$('#year').textContent=new Date().getFullYear();save();render();
